-- Populate or reset team rosters (48 players). Run in Supabase SQL Editor.
-- Requires tables from schema.sql.

insert into teams (name, rank, total_to_par, score_display) values
  ('CHUCK', null, 0, 'E'),
  ('GG', null, 0, 'E'),
  ('EMIL', null, 0, 'E'),
  ('SKIP', null, 0, 'E'),
  ('BHO', null, 0, 'E'),
  ('MORC', null, 0, 'E')
on conflict (name) do nothing;

delete from pool_players;

insert into pool_players (team_name, full_name) values
  ('CHUCK', 'Scottie Scheffler'),
  ('CHUCK', 'Robert MacIntyre'),
  ('CHUCK', 'Min Woo Lee'),
  ('CHUCK', 'Justin Thomas'),
  ('CHUCK', 'Shane Lowry'),
  ('CHUCK', 'Patrick Cantlay'),
  ('CHUCK', 'Daniel Berger'),
  ('CHUCK', 'Sergio Garcia'),
  ('GG', 'Ludvig Åberg'),
  ('GG', 'Hideki Matsuyama'),
  ('GG', 'Justin Rose'),
  ('GG', 'Si Woo Kim'),
  ('GG', 'J.J. Spaun'),
  ('GG', 'Jacob Bridgeman'),
  ('GG', 'Gary Woodland'),
  ('GG', 'Ben Griffin'),
  ('EMIL', 'Bryson DeChambeau'),
  ('EMIL', 'Collin Morikawa'),
  ('EMIL', 'Brooks Koepka'),
  ('EMIL', 'Russell Henley'),
  ('EMIL', 'Sam Burns'),
  ('EMIL', 'Jake Knapp'),
  ('EMIL', 'Max Homa'),
  ('EMIL', 'Wyndham Clark'),
  ('SKIP', 'Jon Rahm'),
  ('SKIP', 'Tommy Fleetwood'),
  ('SKIP', 'Jordan Spieth'),
  ('SKIP', 'Viktor Hovland'),
  ('SKIP', 'Adam Scott'),
  ('SKIP', 'Tyrrell Hatton'),
  ('SKIP', 'Marco Penge'),
  ('SKIP', 'Kurt Kitayama'),
  ('BHO', 'Rory McIlroy'),
  ('BHO', 'Xander Schauffele'),
  ('BHO', 'Patrick Reed'),
  ('BHO', 'Jason Day'),
  ('BHO', 'Corey Conners'),
  ('BHO', 'Maverick McNealy'),
  ('BHO', 'Cameron Smith'),
  ('BHO', 'Brian Harman'),
  ('MORC', 'Cameron Young'),
  ('MORC', 'Matt Fitzpatrick'),
  ('MORC', 'Akshay Bhatia'),
  ('MORC', 'Chris Gotterup'),
  ('MORC', 'Sepp Straka'),
  ('MORC', 'Nicolai Højgaard'),
  ('MORC', 'Harris English'),
  ('MORC', 'Nico Echavarria');
